name: Daemon Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd daemon
          cp core/constants.py.in core/constants.py
          sed -i 's/required=True/required=False/g' core/emulator/coreemu.py
          poetry install
      - name: isort
        run: |
          cd daemon
          poetry run isort -c -df
      - name: black
        run: |
          cd daemon
          poetry run black --check .
      - name: flake8
        run: |
          cd daemon
          poetry run flake8
      - name: grpc
        run: |
          cd daemon/proto
          poetry run python -m grpc_tools.protoc -I . --python_out=.. --grpc_python_out=.. core/api/grpc/*.proto
      - name: test
        run: |
          cd daemon
          poetry run pytest --mock tests
